export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_SUCCESS";

// export const GET_DETAIL_REQUEST = "GET_DETAIL_REQUEST";
// export const GET_DETAIL_SUCCESS = "GET_SUCCESS";
// export const GET_DETAIL_FAIL = "GET_DETAIL_SUCCESS";

export const SET_PRODUCTS_REQUEST = "SET_PRODUCTS_REQUEST";
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_FAIL = "SET_PRODUCTS_SUCCESS";
